name: Automated Testing

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run test cases
        run: |
          python3 find_lowest_number.py test_data/test1_input.txt test1_output.txt
          python3 find_lowest_number.py test_data/test2_input.txt test2_output.txt
          python3 find_lowest_number.py test_data/test3_input.txt test3_output.txt

      - name: Compare Outputs
        run: |
          diff test1_output.txt test_data/test1_expected.txt
          diff test2_output.txt test_data/test2_expected.txt
          diff test3_output.txt test_data/test3_expected.txt
